name: Build iOS internal

on:
  push:
    branches: ['main']

jobs:
  build_ios:
    name: Build iOS Internal
    type: build
    params:
      platform: ios
      profile: preview
      refresh_ad_hoc_provisioning_profile: true

